@echo off
setlocal enabledelayedexpansion

echo.
echo ========================================
echo   WTT Release Publish Configuration
echo ========================================
echo.

REM Check if GitHub CLI is installed
where gh >nul 2>&1
if !ERRORLEVEL! neq 0 (
    echo [ERROR] GitHub CLI gh is not installed or not in PATH
    echo Install from: https://cli.github.com/
    pause
    exit /b 1
)

REM Check GitHub authentication
gh auth status >nul 2>&1
if !ERRORLEVEL! neq 0 (
    echo [WARNING] GitHub CLI is not authenticated
    echo Run: gh auth login
    pause
    exit /b 1
)

echo [OK] GitHub CLI is authenticated

REM Get API Keys from user and save to config file
echo.
echo Enter your GitHub Token (personal access token with repo scope)
set /p GITHUB_TOKEN="GitHub Token: "

echo.
echo Enter your NuGet API Key
set /p NUGET_APIKEY="NuGet API Key: "

REM Create publish-config.bat in the same directory as this script
set CONFIG_FILE=%~dp0publish-config.bat

(
    echo @echo off
    echo REM Auto-generated by setup-publish.bat
    echo set GitHubToken=%GITHUB_TOKEN%
    echo set NuGetAPIKey=%NUGET_APIKEY%
) > "!CONFIG_FILE!"

if !ERRORLEVEL! equ 0 (
    echo.
    echo [OK] Configuration saved to publish-config.bat
) else (
    echo [ERROR] Failed to save configuration
    pause
    exit /b 1
)

echo.
echo ========================================
echo   Setup Complete!
echo ========================================
echo.
echo Your API keys have been saved to: publish-config.bat
echo.
echo To publish a release:
echo   1. Open your project in Rider
echo   2. Change Configuration from Release to Publish
echo   3. Build the project
echo.
echo That's it! The script will handle:
echo   - Zipping the build folder
echo   - Creating a GitHub release and tag
echo   - Publishing to NuGet
echo.
pause
endlocal
